import Link from 'next/link'

import './globals.scss'

export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <div className='flex justify-center relative mt-5'>
              <svg className="h-7 w-7 absolute left-8 top-1 text-slate-300" viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  strokeWidth="2"  strokeLinecap="round"  strokeLinejoin="round">
                  <circle cx="11" cy="11" r="8" /> 
                  <line x1="21" y1="21" x2="16.65" y2="16.65" />
              </svg>
              <input className='rounded-xl w-full mx-7 pl-10 py-2' type="text" placeholder='Search' />
          </div>
        </header>

        <main className='mb-24'>
          {children}
        </main>

        <nav className='fixed bottom-0 left-0 py-7 px-8 rounded-t-[30%] bg-white w-full flex justify-around'>
          <Link href='#'>
            <svg className="h-8 w-8 text-blue-400" viewBox="0 0 24 24" fill="#60a5fa" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><g id="Home"><path d="M21.12,9.79l-7-7a3.08,3.08,0,0,0-4.24,0l-7,7A3,3,0,0,0,2,11.91v7.18a3,3,0,0,0,3,3H9v-6a3,3,0,0,1,6,0v6h4a3,3,0,0,0,3-3V11.91A3,3,0,0,0,21.12,9.79Z" /></g></svg>
          </Link>
          <Link href='#'>
            <svg className="h-8 w-8 text-gray-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">  <circle cx="9" cy="21" r="1" />  <circle cx="20" cy="21" r="1" />  <path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6" /></svg>
          </Link>
          <Link href='#'>
            <svg className="h-8 w-8 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
            </svg>
          </Link>
        </nav>
      </body>
    </html>
  )
}
